default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: mysqlserver.com
  username: esns
  password: minxing123

development:
  <<: *default
  database: yeung

test:
  <<: *default
  database: yeung

production:
  <<: *default
  database: yeung
